### ISSUE TITLE
FE 기술스택 확정 

### ISSUE THREAD

**Issue by JungSWon** [HoorayDev/dev-quiz#3]
정해진 기술 스택 외에 자잘한 기술스택 선정하기 
- 컴포넌트 라이브러리 
- 배포도구 
- 등

**Comment by JungSWon** [comment]
리액트쿼리 선정이유 : https://www.frontendmag.com/insights/react-query-vs-apollo-client/

**Comment by JungSWon** [comment]
[고려해보고 싶은 기술스택]
- [SWR](https://swr.vercel.app/ko) : vercel에서 만든 fetch 훅인데 아주 훌륭한 모듈임
- axios : 이안추천
- baseUI + styletron : atomic CSS를 알고있음을 어필하기 위해 
- [Framer Motion](https://www.framer.com/motion/) : 진짜 잘 활용해보고싶은 컴포넌트 애니메이션 라이브러리 
- [chartjs](https://www.chartjs.org/) : 잘 활용해보고싶은 차트 라이브러리

**Comment by Yu-jae-min** [comment]
[ 고려해보고 싶은 기술스택 ]
- [redux toolkit](https://redux-toolkit.js.org/) or [redux](https://redux.js.org/) : 저희 서비스에서는 아폴로 클라이언트를 통해 캐싱하여 글로벌 데이터를 관리했었는데 범용적으로 사용되는 리덕스(혹은 리덕스 툴킷)를 다시 한번 사용해보고 싶습니다.
- redux middleware ([thunk / saga](https://velog.io/@0715yk/FE-Redux-Thunk-RTK-vs-Redux-Saga)) : 리덕스를 사용하게 된다면 청크/사가도 함께 사용해보고 싶습니다.
- [scss/sass](https://sass-lang.com/) : css in js보다 css 전처리기인 scss를 사용해보고 싶습니다. css in js와 css 모듈에 대해 비교해본 적이 있었는데 css in js는 자바스크립트 해석 과정이 필요하기 떄문에 속도는 css 모듈이 더 빠르고 동적 스타일링은 css in js가 더 편하다고 알고 있습니다. 만약 저희 사이드 프로젝트에 동적 스타일링(state를 통한 스타일 변화)이 많이 필요하지 않다고 하면 매치아크에서 사용하던 css in js, atomic css가 아닌 가볍고 빠른 scss를 사용해보고 싶습니다.
- ESLint + Prettier : 매치아크에서는 두 가지를 함께 활용하지 않았었는데 이 두 가지 설정하는 것도 매우 중요한 것으로 알고 있습니다. 충돌을 해결하고 두 가지를 함께 사용하고 싶습니다.
- [react-i18next](https://velog.io/@hyounglee/TIL-80) : 당장은 아니지만 다국어 서비스를 운영해보고 싶습니다.
- react hook form
