### ISSUE TITLE
[FE] refactor & QA

### ISSUE THREAD

**Issue by JungSWon** [HoorayDev/dev-quiz#33]
### 팀소개 - Mia
- [x] 타이틀 밑줄 (Jay)
- [x] 모바일 화면 팀이미지 줄이기

### 결과페이지 - Mia
- [x] 정답/오답 개수 UI 수정 

### 서비스 전반 - Mia
- [x] [1] 모바일 UI 대응 필요
    - [x] Figma UI 작업
    - [x] main
    - [x] introduction
    - [x] play
    - [x] result
    - [x] incorrect
    - [x] header
- [x] [1] 푸터 붙이기
- [x] [1] 토스트 포지션 이슈 및 색상 변경 필요, 크기 및 색상 변경 필요 -> 토스트 노출 시 잘 보이지 않음
- [x] [1] Production 에서 console log 제거

### 헤더 - Mia
- [x] [3] 헤더 로고 클릭 시 홈 이동
- [x] [3] 헤더 메뉴 클릭 영역 확장 필요

### Progress Page - Jay
- [x] [1] 스플래시(로딩 페이지) 포지션 이슈 -> 로딩 스피너 추가로 대체
- [x] [2] 새로고침 시 경고 모달 노출 후 ok 버튼 클릭 시 홈으로 이동
- [x] [3] userVoteList 10개 응답전에 api 발송 됨 -> api에서 막고는 있긴 하지만, 추후 고쳐야할 부분일거라고 생각이 듭니다..!

### result page - Mia
- [x] [1] 결과 공유하기 버튼 숨김 처리
- [x] [2] 새로고침 시 경고 모달 노출 후 ok 버튼 클릭 시 홈으로 이동 (Jay)
- [x] [3] 문제 업데이트 시 알림 받을 이메일을 입력" 문구 좀더 친절하게 수정

### incorrect page - Jay
- [x]  [1] 유저가 선택한 번호보다 정답 스타일이 우선되어야 함, 선택한 번호 스타일이랑 정답이랑 헷갈릴듯 함 (제안 : 선택했는데 틀린 선택지는 노란색->짙은 회색 수정하면 어떨까요)
- [x]  [1] 정답을 맞춘 경우 문제 해설 보기 텍스트 박스 내부에서 정답 표시 안됨, 틀린 경우는 표시되고 있음
- [x]  [2] 새로고침 시 경고 모달 노출 후 ok 버튼 클릭 시 홈으로 이동
- [x]  [2] 페이지 바닥에 홈으로 가기 또는 스크롤 위로 올리기 등 유저경험 개선 필요 -> 헤더 고정으로 대체
- [x]  [2] 문제에 문항번호가 있으면 좋을 것 같아요 -> title이 남을 예정, Q1 Q2 등은 클라이언트에서 핸들링
- [x]  [3] cursor : default 로 하는게 좋아보임
- [x]  [3] 문제 해설 줄바꿈 처리 추가

### Patch Note Page - Ian & Mia
- [x] [2] 베타버전 내용정리 필요
- [x] [2] 패치노트 업데이트

**Comment by 2Ruk** [comment]
- incorrect page 에서 LINK는 제거

**Comment by Yu-jae-min** [comment]
- [ ] [전체] 반응형 적용, 회의 때 페이지별 레이아웃, 폰트 사이즈 등 논의 후 작업
- [ ] [전체] 푸터 없음
- [ ] [전체] font line height 정돈 필요
- [ ] [전체] 쿠키가 필요한 페이지에서 새로고침 시 홈으로 이동 논의
- [ ] [홈] 헤더 로고 클릭 시 홈 이동
- [ ] [전체] 토스트 포지션 이슈 및 색상 변경 필요, 크기 및 색상 변경 필요 -> 토스트 노출 시 잘 보이지 않음
- [ ] [플레이] 스플래시(로딩 페이지) 포지션 이슈
- [ ] [플레이] 문제 타이틀 넘버링 추가 필요, Q1 Q2...
- [ ] [결과] 결과 공유하기 버튼 숨김 처리
- [ ] [해설] 정답(노랑) 혹은 제출자가 제출한 정답만 보여주는 방향 논의 (정답인 경우 노랑, 틀린 경우 빨강으로 표시)
- [ ] [해설] 컴포넌트 간 간격 정리 필요
- [ ] [해설] 정답을 맞춘 경우 문제 해설 보기 텍스트 박스 내부에서 정답 표시 안됨, 틀린 경우는 표시되고 있음

**Comment by 2Ruk** [comment]
- [ ] 중복 닉네임에 대한 error 핸들링
- [ ] Production 에서 console log 제거 
- [ ] 문제 진행중 animation page 표시 ( 잠깐 표시되었다가 없어짐 ) 
- [ ] userVoteList 10개 응답전에 api 발송 됨 -> api에서 막고는 있긴 하지만, 추후 고쳐야할 부분일거라고 생각이 듭니다..!

----
- 전반적으로 UI위주로 개선하면 좋을 것 같아요! 내일 오전에 미팅을 통해 잡아나가면 좋을 것 같숨니다!

**Comment by Yu-jae-min** [comment]
서비스 전반 - Mia
* [1] 모바일 UI 대응 필요 (모든 페이지가 필요해 보입니다.) -> 전체적인 디자인 관련 논의
* [1] 푸터 붙이기
* [1] 토스트 포지션 이슈 및 색상 변경 필요, 크기 및 색상 변경 필요 -> 토스트 노출 시 잘 보이지 않음
* [1] Production 에서 console log 제거


헤더 - Mia
* [3] 헤더 로고 클릭 시 홈 이동
* [3] 헤더 메뉴 클릭 영역 확장 필요


Progress Page - Jay
- [1] 스플래시(로딩 페이지) 포지션 이슈 -> 로딩 스피너 추가로 대체
- [3] userVoteList 10개 응답전에 api 발송 됨 -> api에서 막고는 있긴 하지만, 추후 고쳐야할 부분일거라고 생각이 듭니다..!
- [2] 새로고침 시 경고 모달 노출 후 ok 버튼 클릭 시 홈으로 이동


result page - Mia
* [2] 새로고침 시 경고 모달 노출 후 ok 버튼 클릭 시 홈으로 이동
* [3] 문제 업데이트 시 알림 받을 이메일을 입력" 문구 좀더 친절하게 수정
* [1] 결과 공유하기 버튼 숨김 처리


incorrect page - Jay
* [2] 새로고침 시 경고 모달 노출 후 ok 버튼 클릭 시 홈으로 이동
* [3] cursor : default 로 하는게 좋아보임
* [2] 페이지 바닥에 홈으로 가기 또는 스크롤 위로 올리기 등 유저경험 개선 필요 -> 헤더 고정으로 대체
* [1] 유저가 선택한 번호보다 정답 스타일이 우선되어야 함, 선택한 번호 스타일이랑 정답이랑 헷갈릴듯 함 (제안 : 선택했는데 틀린 선택지는 노란색->짙은 회색 수정하면 어떨까요)
* [2] 문제에 문항번호가 있으면 좋을 것 같아요 -> title이 남을 예정, Q1 Q2 등은 클라이언트에서 핸들링
* [1] 정답을 맞춘 경우 문제 해설 보기 텍스트 박스 내부에서 정답 표시 안됨, 틀린 경우는 표시되고 있음


Patch Note Page - Ian
* [2] 베타버전 내용정리 필요
