### ISSUE TITLE
Domain Setting

### ISSUE THREAD

**Issue by JungSWon** [HoorayDev/dev-quiz#34]
- 티켓 수정 하여 사용

**Comment by 2Ruk** [comment]
배포 URL:  https://hooray-dev-quiz.netlify.app/

추후 반영 필요 
- 구매 Domain 사용
- SSL 인증서 발급 ( #2 )

**Comment by 2Ruk** [comment]
- [ ] Route 53 설정 
- [ ] 도메인 Record 설정
- [ ] SSL 인증서 받기 ( Certificate Manager )
- [ ] Route 53 Record에 SSL name 추가
- [ ] Application LoadBalancer에 SSL 인증
- [ ] Domain Setting ( api, app )
- [ ] https://api.devquiz.co.kr
- [ ] https://app.devquiz.co.kr

**Comment by 2Ruk** [comment]
Http-> Https Redirect 설정
- [ ] https://api.devquiz.co.kr
