### ISSUE TITLE
도메인 구입

### ISSUE THREAD

**Issue by 2Ruk** [HoorayDev/dev-quiz#5]
- 도메인 구입 리서치
- 사이트: namecheap, 가비아 등 고려
- namecheap 이 저렴

**Comment by JungSWon** [comment]
- devquiz.com 이미 있음 
- https://hooray.devquiz.com/  추천합니다!

**Comment by 2Ruk** [comment]
- 최상위 도메인 기준 ( 가비아 ) 
- ezquiz.co.kr  ( 15,000 원 ) ( api.ezquiz.co.kr , app.ezquiz.co.kr  ) 
- smallquiz.co.kr ( 15,000 원 ) 
- growquiz.com ( 15,000 원 )

**Comment by Yu-jae-min** [comment]
hooray-quiz.com

**Comment by 2Ruk** [comment]
![Image](https://user-images.githubusercontent.com/94098919/236714813-4f0fcca0-f8d0-4899-80b3-6bfa0496209f.png)
