### ISSUE TITLE
디자인 리서치

### ISSUE THREAD

**Issue by 2Ruk** [HoorayDev/dev-quiz#6]
기본 디자인 리서치

**Comment by JungSWon** [comment]
대표적 퀴즈 사이트 : 
https://kahoot.it/   
https://www.quizn.show/


<img src="https://user-images.githubusercontent.com/45927473/236692449-9de78de4-d533-4ca0-9e31-1f6aa715095a.png"
     width="300px" />
---
문답 기본 디자인 : https://kr.vonvon.me/ 

<img src="https://user-images.githubusercontent.com/45927473/236692492-c6770dc0-8c93-484e-8bd9-99da582733ee.png"
     width="300px" />

---
커여움 : https://pokemon.itple.co.kr/ 
댓글, 랭킹, 등급 모두 다룸 

<img src="https://user-images.githubusercontent.com/45927473/236692746-9acadc72-c635-4741-9ecf-be7bc9841577.png"
     width="200px" /> <img src="https://user-images.githubusercontent.com/45927473/236693104-9cab93f5-0475-4115-b94c-067fc0d57e19.png"
     width="200px" /> <img src="https://user-images.githubusercontent.com/45927473/236693115-6c2a7c9f-32bc-449c-b24d-9597b4274d23.png"
     width="200px" />

---

외 : https://www.quizland.kr/
![image](https://user-images.githubusercontent.com/45927473/236693199-b3a3ff5f-86a6-4c00-a3e5-59e66311f2af.png)

**Comment by 2Ruk** [comment]
[ 리소스 참고 ]


![Image](https://user-images.githubusercontent.com/94098919/236710888-1d879777-a3df-4685-ab69-bf5058e567d8.png)



![Image](https://user-images.githubusercontent.com/94098919/236711827-2838632f-30eb-4fc4-a8eb-d826d6f6ba6e.png)



![Image](https://user-images.githubusercontent.com/94098919/236711914-db692a54-9174-45a0-9186-e0656a4e41fe.png)




[ 기타 ] 
- 교재: https://www.bookdonga.com/element/book_view.donga?product_seq=32849
- 설문 사이트: https://www.heypoll.co.kr/poll?selectedSurveyId=627413
- threejs 활용: https://twitter.com/bayazuman/status/1521133894665670656?s=20&t=HkHryo-J9e1wNZdK-h40rw
